[BoW] Added sample code
hyunggi-sv/bow_sample_codes pull request #2
Opened 2021-08-13 00:01 UTC by binue97

# Background
- DBoW2와 FBoW를 사용하는 sample code를 작성해 달라는 요청을 받았습니다.

# Actions
- CMakeLists.txt에 easy profiler를 찾아서 함께 빌드할 수 있게끔 해주었습니다.
  - find_package 명령어를 통해 easy profiler를 찾습니다.
- ORB Vocabulary 파일을 사용하였습니다.
- 간단한 Unit test를 작성하였습니다.
  - 4개의 Database 이미지에서 Query 이미지와 가장 유사한 이미지를 찾아서 저장하는 기능을 합니다.
  - [DBoW2] source code : DBoW2/DBoW2_sample_code.cpp
  - [FBoW] source code : FBoW/FBoW_sample_code.cpp

# Test results
- Database images
![Screenshot from 2021-08-12 14-04-14](https://user-images.githubusercontent.com/63780124/129284578-4c4131a2-2b86-48f9-8750-49f2cb77cd0b.png)

- Query image
![Screenshot from 2021-08-12 15-31-34](https://user-images.githubusercontent.com/63780124/129284639-ad63c2c3-1493-46ea-b093-054fa2ea10e3.png)

- Result 
![Screenshot from 2021-08-10 13-10-04](https://user-images.githubusercontent.com/63780124/129284668-7eeb5981-d607-436f-9e36-c113a7487dbd.png)

- Easy profiler를 통한 profiling 결과 화면
![Screenshot from 2021-08-10 13-24-41](https://user-images.githubusercontent.com/63780124/129284695-93917bb3-41f9-4723-baeb-11c745a9d282.png)

2021-08-13 05:10 UTC, binue97 commented on DBoW2/DBoW2_sample_code.cpp
> +void wait()
wait 함수를 그냥 제거 해도 괜찮을까요?!
굳이 중간에 멈추는 건 불필요한 것 같기도 해서요..!!

2021-08-13 05:16 UTC, binue97 commented on DBoW2/DBoW2_sample_code.cpp
> +      cerr << "Falied to open at: " << vocPath << endl;
이 부분은 Newline 하나를 추가 하라는 말씀이신가요??!

2021-08-13 06:00 UTC, binue97 commented on DBoW2/DBoW2_sample_code.cpp
> +void loadDBFeatures(vector<vector<cv::Mat > > &features);
loadDBFeatures, loadQueryFeatures 함수 초반에 features.clear(), features.reserve() 때문에 const를 붙일 수가 없었습니다!
clear(), reserve()는 기존 DBoW 코드에서 사용하길래 그대로 사용했었습니다. 
* const를 넣고 clear(), reserve()를 빼는 방법이 있고
* const를 빼고 clear(), reserve()를 넣는 방법이 있는데 
어떤 것으로 하면 될까요?

2021-08-13 06:27 UTC, binue97 commented on DBoW2/DBoW2_sample_code.cpp
> +void loadVocabulary(OrbVocabulary* vobabulary);
loadVocabulary에서 loadFromTextFile()을 호출할 때 const 타입으로는 함수를 사용할 수 없어서 const 없이 pass-by-reference로 수정하였습니다!

이유를 좀 찾아보니
const type의 object에서는 non-const method를 호출할 수가 없다고 합니다!

2021-08-13 06:39 UTC, binue97 commented on DBoW2/DBoW2_sample_code.cpp
> +void loadDBFeatures(vector<vector<cv::Mat > > &features);
제가 Aliasing 을 위해 `std::vector<std::vector<cv::Mat>>` 를 `FeatureVector` 로 정의하려고 했는데, DBoW 폴더 내에 FeatureVector.h 라는 헤더가 있고 거기서 이미 사용하고 있는 변수 이름이었습니다.
그래서 `DescriptorVector` 로 사용을 했습니다.

그런데 만일 `FeatureVector` 가 최적의 변수명이라서 꼭 이 이름을 사용하고 싶은 경우에는 어떤 방법으로 이걸 사용할 수 있을까요..?

2021-08-13 07:31 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +void wait()
넵 제거해도 좋을 것 같습니다 :)

2021-08-13 07:32 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +void loadDBFeatures(vector<vector<cv::Mat > > &features);
아 변형되는군요! 제가 잘못읽은 것 같네요 ㅎㅎ...
const 를 빼고 clear(), reserve()를 넣는게 좋은 것 같습니다

2021-08-13 07:33 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +void loadDBFeatures(vector<vector<cv::Mat > > &features);
namespace를 걸어주면 좋을 것 같습니다.

2021-08-13 08:23 UTC, binue97 commented on FBoW/FBoW_sample_code.cpp
> +vector< cv::Mat  >  loadFeatures(std::string imgPath, const int imgNum, string descriptor);
아래의 Comment와 함께 적용이 어려울 것 같습니다. 
constexpr로 선언한 변수를 인자로 받을 때는 타입을 맞춰주어야 하는 것 같습니다

2021-08-17 08:14 UTC, binue97 commented on FBoW/FBoW_sample_code.cpp
> +#endif
Switch case의 표현식에는 정수형의 타입만 지원하는 것으로 알고 있는데 
구글링을 해보니 해쉬함수를 통해 구현할 수 있다고 하더라구요! 
혹시 이것을 사용해서 구현하는 것이 맞을까요?

수정된 코드에서는 surf와 akaze가 사용되지 않아서  if, else if , else로 간단하게 정리되는데 이럴 경우엔 if/else 형태가 오히려 좋은가요?

2021-08-18 04:29 UTC, hyunggi-sv commented on FBoW/FBoW_sample_code.cpp
> +#endif
switch case를 사용하면서 명시적으로 타입을 표현할 때는 enum class을 사용하면 좋습니다.

```cpp
enum class FeatureType
{
 ORB = 0,
 AKAZE = 1,
 BRISK = 2,
 SURF = 3
};

int main()
{
    FeatureType feat = FeatureType::ORB;
    
    switch (feat) 
    { 
      case FeatureType::ORB:
        std::cout << "ORB";
        break;
      
      case FeatureType::AKAZE:
        std::cout << "AKAZE";
        break;
      
      case FeatureType::BRISK:
        std::cout << "BRISK";
        break;
      
      case FeatureType::SURF:
        std::cout << "SURF";
        break;
      
      default:
        std::cout << "Unknown";
        break;
    }
}
```


surf와 akaze를 사용하지 않으면 그냥 다 빼버리셔도 됩니다 ㅎㅎ

2021-08-18 05:31 UTC, binue97 commented on DBoW2/DBoW2_sample_code.cpp
> +    changeStructure(descriptors, features.back());
이 부분은 살펴봤는데 DBoW2 Demo code의 API가 조금 부자연스러운 것 같습니다. 
DBoW2는 loadFeature()라는 함수를 main()에서 한번 호출을 하고 loadFeature()함수 내에서 changeStructure()를 통해 형식을 맞춰주었구요

FBoW에서는 좀 다르게 loadFeature()를 main에서 여러번 반복적으로 호출을 하였지만, loadFeature()내부에서는 따로 changeStructure()를 통해 형식을 맞춰주지 않아도 되게끔 해주었습니다.

2021-08-19 01:54 UTC, hyunggi-sv reviewed
고생하셨습니다!
조금만 더 수정해주시면 될 것 같습니다

2021-08-19 01:54 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +namespace UnitTest
이 코드에는 unit test가 포함되지 않기 때문에 `UnitTest` namespace는 적절하지 않은 것 같습니다.

2021-08-19 01:54 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +bool loadDBFeatures(UnitTest::FeatureVector &vfeatures, UnitTest::FileLUT &dbTable, const cv::Ptr<cv::ORB> &orb);
```suggestion
bool loadDBFeatures(UnitTest::FeatureVector& vfeatures, UnitTest::FileLUT& dbTable, const cv::Ptr<cv::ORB>& orb);

```

저희 코딩 가이드라인에서는 &는 변수명이 아닌 타입에 붙습니다. (이 쪽이 좀 더 가독성 높아요! :smile_cat: )

아래 다른 함수들에도 적용해주시면 좋을 것 같습니다

2021-08-19 01:54 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +fs::path vocPath("../ORBvoc/ORBvoc.txt");
Windows 환경에서는 경로를 탐색할 때 `/`를 사용하면 문제가 생기기도 합니다.
그러므로 filesystem에서 지원하는 경로 탐색 방법을 사용하면 좋습니다. 
fs::current_path()를 사용하시고, 거기서부터 디렉토리 이동하는 방법을 참조하시면 좋을 것 같아요.

2021-08-19 01:54 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +  std::unique_ptr<OrbVocabulary> ptrVocabulary(new OrbVocabulary());
```suggestion
  auto ptrVocabulary = std::make_unique<OrbVocabulary>();

```

smart pointer를 만들때는 `new`는 사용하지 않습니다.
make_unique, make_shared를 사용합니다

2021-08-19 01:54 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +  std::unique_ptr<OrbVocabulary> ptrVocabulary(new OrbVocabulary());
다른 코드에도 적용 부탁드립니다!

2021-08-19 01:54 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +  for(fs::directory_iterator it(dbPath); it != fs::end(it); it++)
```suggestion
for (const auto& entry : dbPath)

```
뭔가 느낌상 이게 될 것 같다는 생각이 드는군요...!
Range-based for loop 방식인데, 이 방법 한번 사용해보시겠어요? 안돌아가면 수정 안하셔도 됩니다

2021-08-19 01:54 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +    std::string fileName = entry.path();
```suggestion
    const std::string fileName = entry.path();

```

2021-08-19 01:54 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +    if(image.empty()) return false;
```suggestion
    if(image.empty()) 
        return false;

```

2021-08-19 01:54 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +    vfeatures.push_back(UnitTest::Features());
```suggestion
    vfeatures.emplace_back(UnitTest::Features());

```

2021-08-19 01:54 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +  if(!voc.loadFromTextFile(vocPath))  return false;
```suggestion
  if(!voc.loadFromTextFile(vocPath))  
      return false;

```

2021-08-19 01:54 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +  for(fs::directory_iterator it(queryPath); it != fs::end(it); it++)
여기도 range-based for loop 적용 테스트 해주세요 :smile:

2021-08-19 01:54 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +  if(nCandidates > NQUERYIMAGES)  return false;
```suggestion
  if(nCandidates > NQUERYIMAGES)  
      return false; 

```

2021-08-19 01:54 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +    queryResultTable.push_back(dbTable[ret[0].Id]);
```suggestion
    const auto& bestMatch = dbTable[ret[0].Id]);
    queryResultTable.push_back(bestMatch);

```
Reference variable을 이용해서 가독성을 높일 수 있습니다.

2021-08-19 01:54 UTC, hyunggi-sv commented on FBoW/FBoW_sample_code.cpp
> +        for (size_t j = 0; j < dbFeatures.size(); j++)
size_t 대신 명시적인 타입을 사용해야합니다.
Feature의 크기를 파악해서 적절한 타입을 넣어주세요 :smile_cat:

2021-08-19 01:54 UTC, hyunggi-sv commented on FBoW/FBoW_sample_code.cpp
> +    else throw std::runtime_error("Invalid descriptor");
```suggestion
    assert(descriptor == "orb" || descriptor == "brisk");
    if (descriptor == "orb") fdetector = cv::ORB::create(2000);
    if (descriptor == "brisk") fdetector = cv::BRISK::create();
```
assert로 exception 체크를 해주는 것도 좋습니다

2021-08-19 02:27 UTC, binue97 commented on DBoW2/DBoW2_sample_code.cpp
> +namespace UnitTest
작명은 정말 창작의 고통이군요... 
SampleCode로 수정했는데 괜찮을까요? (썩 마음에 들지는 않습니다만 ㅠㅠ)

2021-08-20 01:19 UTC, binue97 commented on DBoW2/DBoW2_sample_code.cpp
> +  for(fs::directory_iterator it(dbPath); it != fs::end(it); it++)
dbPath를 넣어주면 컴파일 에러가 나서 
`fs::directory_iterator it(dbPath);
 for(const auto& entry : it) `
이런 식으로 작성했는데 괜찮을까요?

2021-08-20 05:00 UTC, binue97 commented on DBoW2/DBoW2_sample_code.cpp
> +  for(fs::directory_iterator it(dbPath); it != fs::end(it); it++)
바로 dbPath를 넣어주면 컴파일 에러가 나서 
`for(const auto& entry : fs::directory_iterator(dbPath)`
이런식으로 작성했는데 괜찮을까요?

2021-08-21 13:14 UTC, hyunggi-sv requested changes
코드가 점점 좋아지고 있습니다 ㅎㅎ
마지막 한번만 수정 부탁드립니다!

함수 인자로 pointer의 내용물을 넘기는거보다, pointer 자체를 넘기는게 좀 더 좋습니다. 
이 방식을 사용하면 1. 코드의 가독성이 좋아지고, 2. nullptr가 넘어왔을 때 케이스를 작성할 수 있습니다.
nullptr가 괜찮은 거라면 `if (ptrVariable == nullptr) return false;` 등으로 할 수 있고, nullptr가 설계상 존재하면 안되는거라면 `assert(ptrVariable != nullptr)`을 써서 에러를 방지할 수 있습니다.

2021-08-21 13:14 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +  auto ptrDatabase = std::make_unique<OrbDatabase>(*ptrVocabulary);
```suggestion
  auto& vocabulary = *ptrVocabulary;
  auto ptrDatabase = std::make_unique<OrbDatabase>(vocabulary);

```
가독성을 높이기 위해 위와 같은 변화를 제안합니다.
어떻게 생각하시나요?

2021-08-21 13:14 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +  if(!createDatabase(*ptrDatabase, dbFeatures))
이 부분도 포인터의 내용물을 넘기기보다는 포인터를 직접 넘기는게 좋을 것 같습니다.

2021-08-21 13:14 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +  if(!queryDatabase(*ptrDatabase, queryFeatures, queryResultTable, dbTable))
이 부분도 포인터의 내용물을 넘기기보다는 포인터를 직접 넘기는게 좋을 것 같습니다.

2021-08-21 13:14 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +    cv::Mat image = cv::imread(fileName, 0);
```suggestion
    const cv::Mat image = cv::imread(fileName, 0);

```

2021-08-21 13:14 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +
```suggestion
```

2021-08-21 13:14 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +
```suggestion
```

2021-08-21 13:14 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +    cv::Mat image = cv::imread(fileName, 0);
```suggestion
    const cv::Mat image = cv::imread(fileName, 0);

```

2021-08-21 13:14 UTC, hyunggi-sv commented on DBoW2/DBoW2_sample_code.cpp
> +
```suggestion
```

2021-08-21 13:14 UTC, hyunggi-sv commented on FBoW/FBoW_sample_code.cpp
> +        cv::Mat image = cv::imread(readPath, 0);
```suggestion
        const cv::Mat image = cv::imread(readPath, 0);
```

2021-08-23 05:13 UTC, binue97 commented on DBoW2/DBoW2_sample_code.cpp
> +{
아 FeatureVector라는 변수명을 사용하고 싶었는데 헤더의 다른 클래스와 이름이 겹쳐서 ambiguous하다고 해서 namespace를 추가했습니다. 

이 예제에서는 반드시 FeatureVector라는 변수명을 사용할 필요는 없으니, DescriptorVector로 수정하겠습니다.
이렇게 하는게 불필요하게 namespace를 붙여서 변수가 길어지는 것도 막아주고 좋을 것 같네요!

2021-08-23 05:32 UTC, binue97 commented on DBoW2/DBoW2_sample_code.cpp
> +  if(!loadVocabulary(*ptrVocabulary))
확실히 nullptr에 대한 예외케이스를 함수에서 편하게 확인할 수 있어서 포인터를 넘기는 방식이 더 나은 것 같습니다! 그렇게 수정하겠습니다!!

2021-08-23 05:37 UTC, binue97 commented on DBoW2/DBoW2_sample_code.cpp
> +  auto ptrDatabase = std::make_unique<OrbDatabase>(*ptrVocabulary);
음 처음에는 de-reference를 사용하여 한 줄로 작성하는게 보기에 깔끔하다고 생각했었는데, 
형기님이 제안하신 코드를 보니 코드를 보는 사람 입장에서 '이해'하기에는 두 줄로 구분해서 Vocabulary를 사용해 Database를 구축한다는 의미가 더 쉽게  와닿을 수 있겠다는 생각이 드네요!! 
반영해서 수정하도록 하겠습니다~ 감사합니다!

2021-08-23 07:55 UTC, hyunggi-sv approved these changes
고생하셨습니다!!!! 
눈부시는 코드입니다 :sunglasses:

2021-08-25 03:46 UTC, merged